### <b>PART 1: Theoretical Questions</b>

**1) What are the different data structures used in Tensorflow?. Give some examples.**

TensorFlow primarily deals with tensors, which are multi-dimensional arrays. Tensors are the fundamental data structures used for representing and manipulating data in TensorFlow.

Here are some of the main data structures used in TensorFlow:

 - Tensor: The basic unit of data in TensorFlow. Tensors are multi-dimensional arrays with a fixed size. It can be mutable or immutable.


In [ ]:
## Examples of tensor
import tensorflow as tf
import numpy as np
ten_1 = tf.constant([27, 10])
ten_2 = tf.constant(np.array([[27, 10, 27], [43, 28, 43]]))

- Variable: A mutable tensor that can be modified during the execution of a program. Variables are often used to represent model parameters.

In [ ]:
ten_var = tf.Variable([27, 10, 26])
print(ten_var.numpy())
print()
ten_var[2].assign(27)
print(ten_var.numpy())

[27 10 26]

[27 10 27]


- Constant: A constant tensor with fixed values that cannot be changed after creation.

In [ ]:
ten_con = tf.constant([27, 10, 26])
print(ten_con.numpy())
print()
# ten_con[2].assign(27) ## This will generate an error, since the constant tensors are immutable.
# print(ten_con.numpy())

[27 10 26]



- RaggedTensor: A tensor with non-uniform shapes along one or more dimensions. It is useful for representing sequences of varying lengths.

In [ ]:
ten_ragged = tf.ragged.constant([[27, 10, 27], [26], [43, 28]])
print(ten_ragged)

<tf.RaggedTensor [[27, 10, 27], [26], [43, 28]]>


2) How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

The main difference between Tensorflow constant and Tensorflow variable is that Tensorflow constants are immutable (cannot be changed after creation) in nature whereas Tensorflow variables are mutable (can be changed after creation) in nature.

In [ ]:
## Try to modify the elements of Tensorflow variable
## This will work properly since they are mutable
ten_var = tf.Variable([27, 10, 26])
print(ten_var.numpy())
print()
ten_var[2].assign(27)
print(ten_var.numpy())

[27 10 26]

[27 10 27]


In [ ]:
## Try to modify the elements of Tensorflow constants
ten_con = tf.constant([27, 10, 26])
print(ten_con.numpy())
print()
ten_con[2].assign(27) ## This will generate an error, since the constant tensors are immutable.
print(ten_con.numpy())

[27 10 26]



AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

3) Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.


In TensorFlow, matrix operations, including addition, multiplication, and element-wise operations, are fundamental operations that involve manipulating tensors.

1. Matrix Addition:
Matrix addition involves adding corresponding elements of two matrices of the same shape. In TensorFlow, you can use the tf.add() function for this operation.

In [ ]:
matrix_1 = tf.constant([[1,2], [3,4]])
matrix_2 = tf.constant([[5,6], [7,8]])

print("matrix 1:\n", matrix_1.numpy())
print()
print("matrix 2:\n", matrix_2.numpy())
print()
print("Addition of Two matrix:\n", tf.add(matrix_1, matrix_2).numpy())

matrix 1:
 [[1 2]
 [3 4]]

matrix 2:
 [[5 6]
 [7 8]]

Addition of Two matrix:
 [[ 6  8]
 [10 12]]


2. Matrix Multiplication:
Matrix multiplication involves multiplying elements of one matrix with corresponding elements of the other matrix and summing the results. In TensorFlow, you can use the tf.matmul() function for matrix multiplication.

In [ ]:
matrix_1 = tf.constant([[1,2], [3,4]])
matrix_2 = tf.constant([[5,6], [7,8]])

print("matrix 1:\n", matrix_1.numpy())
print()
print("matrix 2:\n", matrix_2.numpy())
print()
print("Addition of Two matrix:\n", tf.matmul(matrix_1, matrix_2).numpy())

matrix 1:
 [[1 2]
 [3 4]]

matrix 2:
 [[5 6]
 [7 8]]

Addition of Two matrix:
 [[19 22]
 [43 50]]


3. Element-wise Operations:
Element-wise operations involve performing an operation independently on each element of a matrix. Common element-wise operations include addition, subtraction, multiplication, division, exponentiation, etc. TensorFlow provides element-wise operations through standard arithmetic functions.

In [31]:
matrix_3 = tf.constant([[10, 2], [9, 12]])

## Let's do squaring of each element of a tensor
print("matrix 3:\n", matrix_3.numpy())
print()
print("Square of a matrix:\n", tf.square(matrix_3).numpy())

matrix 3:
 [[10  2]
 [ 9 12]]

Square of a matrix:
 [[100   4]
 [ 81 144]]


In [30]:
import tensorflow as tf

### <b>PART 2: Practical Implementation</b>

**Talk 1: Creating and Manipulating Matricek**

1) Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the
values of matrix A.

In [ ]:
## Creating a normal matrix of dimensions 2x2 from the normal distribution.
random_normal = tf.random.Generator.from_seed(32)
A = random_normal.normal(shape=(3,3))

print("Elements of matrix A:\n",A.numpy())

Elements of matrix A:
 [[ 0.7901182   1.585549    0.4356279 ]
 [ 0.2364518  -0.1589871   1.302304  ]
 [ 0.9592239   0.85874265 -1.5181769 ]]


2) Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [ ]:
## tf.truncated_normal() function discard or re-draw the values which are more than two stddev from the mean.
tf.random.set_seed(32)
B = tf.random.truncated_normal(shape=(4,4)) ## Default value of mean and stddev is 0.0 and 1.0.

print("Elements of matrix B:\n",B.numpy())

Elements of matrix B:
 [[ 0.82033765  0.73500305  1.0454717   0.702631  ]
 [ 0.4472365   0.36746743  0.6453506   1.2794147 ]
 [-0.75372434 -0.176359   -0.10414879  0.74450344]
 [-0.67275274 -1.7532346   0.9149069   0.45171866]]


3) Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values
of matrix C.

In [ ]:
random_normal = tf.random.Generator.from_seed(32)
C = random_normal.normal(shape=(2,2), mean=3, stddev=0.5)

print("Elements of matrix C:\n",C.numpy())

Elements of matrix C:
 [[3.395059  3.7927744]
 [3.217814  3.1182258]]


4) Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [33]:
## Over here, we will get a error as the dimensions of previously created matrices, A and B are not same.
## Let's create other matrices with the same method but having same dimensions

random_normal = tf.random.Generator.from_seed(32)
A = random_normal.normal(shape=(2,3))

print("Elements of matrix A:\n",A.numpy())
print()

tf.random.set_seed(32)
B = tf.random.truncated_normal(shape=(2,3))

print("Elements of matrix B:\n",B.numpy())
print()

D = tf.add(A, B)
print("Elements of D is:\n",D.numpy())

Elements of matrix A:
 [[ 0.7901182  1.585549   0.4356279]
 [ 0.2364518 -0.1589871  1.302304 ]]

Elements of matrix B:
 [[0.82033765 0.73500305 1.0454717 ]
 [0.702631   0.4472365  0.36746743]]

Elements of D is:
 [[1.6104559 2.320552  1.4810996]
 [0.9390828 0.2882494 1.6697714]]


5) Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [35]:
E = tf.matmul(C, D)

print("Elements of E:\n", E.numpy())

Elements of E:
 [[ 9.029322   8.971677  11.361487 ]
 [ 8.11042    8.3659315  9.972628 ]]


**Talk 2: Performing Additional Matrix Operations**

1) Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

In [ ]:
## tensorflow.random.uniform() function is used to generate a tensor of given shape from the uniform distribution.
random_uniform = tf.random.Generator.from_seed(32)
F = random_uniform.uniform(shape=(2,2))

2) Calculate the transpose of matrix F and store the result in matrix G.

In [ ]:
print("Before calculating transpose:\n", F.numpy())
G = tf.transpose(F)
print()
print("After calculating transpose:\n", G.numpy())

Before calculating transpose:
 [[0.20822704 0.07357836]
 [0.88440466 0.17085445]]

After calculating transpose:
 [[0.20822704 0.88440466]
 [0.07357836 0.17085445]]


3) Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [ ]:
## Element-Wise Primitive Operations are performed on each elements of a tensor.
print("Before performing element-wise exp:\n", F.numpy())
H = tf.exp(F)
print()
print("After performing element-wise exp:\n", H.numpy())

Before performing element-wise exp:
 [[0.20822704 0.07357836]
 [0.88440466 0.17085445]]

After performing element-wise exp:
 [[1.2314928 1.0763528]
 [2.4215424 1.186318 ]]


4) Create a matrix I by concatenating matrix F and matrix G horizontally.

In [ ]:
print("Matrix F:\n", F.numpy())
print()
print("Matrix G:\n", G.numpy())
I = tf.concat([F, G], axis=1)
print()
print("Result of concatination:\n", I.numpy())

Matrix F:
 [[0.20822704 0.07357836]
 [0.88440466 0.17085445]]

Matrix G:
 [[0.20822704 0.88440466]
 [0.07357836 0.17085445]]

Result of concatination:
 [[0.20822704 0.07357836 0.20822704 0.88440466]
 [0.88440466 0.17085445 0.07357836 0.17085445]]


5) Create a matrix J by concatenating matrix F and matrix H vertically.

In [ ]:
print("Matrix F:\n", F.numpy())
print()
print("Matrix H:\n", H.numpy())
J = tf.concat([F, H], axis=0)
print()
print("Result of concatination:\n", J.numpy())

Matrix F:
 [[0.20822704 0.07357836]
 [0.88440466 0.17085445]]

Matrix H:
 [[1.2314928 1.0763528]
 [2.4215424 1.186318 ]]

Result of concatination:
 [[0.20822704 0.07357836]
 [0.88440466 0.17085445]
 [1.2314928  1.0763528 ]
 [2.4215424  1.186318  ]]
